;; Definitions for hardware VGA 80x30 text display

;; Background color (low nybble of attribute)
HWVGA_BG_BLACK      EQU $00
HWVGA_BG_RED        EQU $01
HWVGA_BG_GREEN      EQU $02
HWVGA_BG_YELLOW     EQU $03
HWVGA_BG_BLUE       EQU $04
HWVGA_BG_MAGENTA    EQU $05
HWVGA_BG_CYAN       EQU $06
HWVGA_BG_GRAY       EQU $07
HWVGA_BG_DK_GRAY    EQU $08
HWVGA_BG_BR_RED     EQU $09
HWVGA_BG_BR_GREEN   EQU $0a
HWVGA_BG_BR_YELLOW  EQU $0b
HWVGA_BG_BR_BLUE    EQU $0c
HWVGA_BG_BR_MAGENTA EQU $0d
HWVGA_BG_BR_CYAN    EQU $0e
HWVGA_BG_WHITE      EQU $0f

;; Foreground colors (high nybble of attribute)
HWVGA_FG_BLACK      EQU $00
HWVGA_FG_RED        EQU $10
HWVGA_FG_GREEN      EQU $20
HWVGA_FG_YELLOW     EQU $30
HWVGA_FG_BLUE       EQU $40
HWVGA_FG_MAGENTA    EQU $50
HWVGA_FG_CYAN       EQU $60
HWVGA_FG_GRAY       EQU $70
HWVGA_FG_DK_GRAY    EQU $80
HWVGA_FG_BR_RED     EQU $90
HWVGA_FG_BR_GREEN   EQU $a0
HWVGA_FG_BR_YELLOW  EQU $b0
HWVGA_FG_BR_BLUE    EQU $c0
HWVGA_FG_BR_MAGENTA EQU $d0
HWVGA_FG_BR_CYAN    EQU $e0
HWVGA_FG_WHITE      EQU $f0

;; vim:ft=asm6809:
