;;**********************************************************************
;; Monitor constants
;;**********************************************************************

;; Character values
CR EQU $0D
NL EQU $0A
SPACE EQU $20
TAB EQU $09
COLON EQU $3A

;; 3.6864 MHz crystal: E clock is 921.6 kHz, divide by 96 to get 9600 bps
ACIA_CLKDIV EQU 6

;; Compute initial value for ACIA control register
;; Note that even though the rx/tx clock is generated by
;; the 82C54 counter/timer, the ACIA /16 divisor is used,
;; because with the /1 divisor, there is no automatic
;; synchronization of the rx/tx data and clocks.
ACIA_INIT EQU (ACIA_CTRL_CLKDIV_16 | ACIA_CTRL_SEL_8N1 | ACIA_CTRL_XMIT_RTS_LOW_TX_INT_DIS | ACIA_CTRL_RX_INT_DIS)

;; Number of characters that can be stored in the command buffer
;; (actual buffer is 1 larger to allow room for the nul terminator.)
;; This size is chosen to allow ihex records with 32 data bytes to
;; be read (these will be 75 bytes).
MONTIOR_MAXCMDLEN equ 99

;; Intel hex record types.
IHEX_DATA EQU 0
IHEX_EOF EQU 1
IHEX_ERROR EQU 99

;; Clearing bit 4 of the condition code register enables
;; regular (IRQ) interrupts.
ENABLE_IRQ EQU 0b11101111

;; Setting bit 4 of the condition code register disables
;; regular (IRQ) interrupts.
DISABLE_IRQ EQU 0b00010000

;; Special values which can be written to the i82c55a control port
;; in order to set and clear bits 0 and 1, which drive the -SET
;; inputs used for detecting edge-triggered interrupts.
;; (When a byte where the high bit is 0 is written to the control port,
;; it sets or resets a single bit in port C. See 82C55A datasheet.)
IRQ3_FF_SET_ASSERT    EQU 0b00000000
IRQ3_FF_SET_DEASSERT  EQU 0b00000001
IRQ6_FF_SET_ASSERT    EQU 0b00000010
IRQ6_FF_SET_DEASSERT  EQU 0b00000011

;; HWVGA stuff
HWVGA_DEFAULT_ATTR    EQU (HWVGA_BG_BLACK|HWVGA_FG_BR_GREEN)

;; vim:ft=asm6809:
;; vim:ts=4:
